global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus-self-monitoring'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'internet-monitor'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 30s
    metrics_path: /metrics
